name: Checkstyle

on:
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_version: 10.9.3
          checkstyle_config: config/checkstyle.xml
          level: error